server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://101.132.147.188:3306/taobao_task?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root0.0
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  typeAliasesPackage: cn.hewei.task.entity
